import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../components/navbar"
import styles from '../styles/Home.module.css'
import Searchbar from "../components/searchbar"
import Filter from "../components/filter"
import Slider from '../components/Slider/slider'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
		<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
    	<main className={styles.main}>

		{ <Navbar />}
			<div className={styles.maincontent}>
			<div className={styles.leftsection}>
				<Filter />

			 <Searchbar />
			</div>
			<div className={styles.rightsection}>

				<Slider/>
			</div>
			</div>


		</main>
    </div>
  )
}
