import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../components/navbar"
import styles from '../styles/Home.module.css'
import Searchbar from "../components/searchbar"
import Filter from "../components/filter"
import Slider from '../components/Slider/slider'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <Navbar />
    	<main className={styles.main}>
	
		<Slider/>

		 <Searchbar />

		<Filter />
		</main>
    </div>
  )
}
